"""baseline v5.1 pilot

Revision ID: 78068b70afbf
Revises: 
Create Date: 2026-09-06 19:54:31.455872
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '78068b70afbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=180), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('source_ip_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('course_day_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language', 'day', name='uq_course_day_result')
    )
    op.create_index(op.f('ix_course_day_results_language'), 'course_day_results', ['language'], unique=False)
    op.create_index(op.f('ix_course_day_results_user_id'), 'course_day_results', ['user_id'], unique=False)
    op.create_table('custom_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('shop', sa.String(length=160), nullable=False),
    sa.Column('topic', sa.String(length=160), nullable=False),
    sa.Column('subtopic', sa.String(length=160), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('term', sa.String(length=500), nullable=False),
    sa.Column('pronunciation', sa.String(length=500), nullable=False),
    sa.Column('translation', sa.String(length=500), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('example_translation', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_terms_language'), 'custom_terms', ['language'], unique=False)
    op.create_index(op.f('ix_custom_terms_public_id'), 'custom_terms', ['public_id'], unique=True)
    op.create_index(op.f('ix_custom_terms_status'), 'custom_terms', ['status'], unique=False)
    op.create_index(op.f('ix_custom_terms_topic'), 'custom_terms', ['topic'], unique=False)
    op.create_table('exam_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_results_language'), 'exam_results', ['language'], unique=False)
    op.create_index(op.f('ix_exam_results_user_id'), 'exam_results', ['user_id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=160), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_game_type'), 'game_sessions', ['game_type'], unique=False)
    op.create_index(op.f('ix_game_sessions_language'), 'game_sessions', ['language'], unique=False)
    op.create_index(op.f('ix_game_sessions_public_id'), 'game_sessions', ['public_id'], unique=True)
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.create_table('gamification_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lifetime_xp', sa.Integer(), nullable=False),
    sa.Column('spendable_xp', sa.Integer(), nullable=False),
    sa.Column('weekly_xp', sa.Integer(), nullable=False),
    sa.Column('week_key', sa.String(length=12), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('learning_nudges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('target_view', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_nudges_created_at'), 'learning_nudges', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_nudges_read'), 'learning_nudges', ['read'], unique=False)
    op.create_index(op.f('ix_learning_nudges_user_id'), 'learning_nudges', ['user_id'], unique=False)
    op.create_table('login_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_sessions_token_hash'), 'login_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_login_sessions_user_id'), 'login_sessions', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('window_start', sa.String(length=5), nullable=False),
    sa.Column('window_end', sa.String(length=5), nullable=False),
    sa.Column('browser_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('practice_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=160), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_results_created_at'), 'practice_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_practice_results_kind'), 'practice_results', ['kind'], unique=False)
    op.create_index(op.f('ix_practice_results_language'), 'practice_results', ['language'], unique=False)
    op.create_index(op.f('ix_practice_results_session_id'), 'practice_results', ['session_id'], unique=True)
    op.create_index(op.f('ix_practice_results_user_id'), 'practice_results', ['user_id'], unique=False)
    op.create_table('term_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('term_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language', 'term_id', name='uq_progress_language_term')
    )
    op.create_index(op.f('ix_term_progress_language'), 'term_progress', ['language'], unique=False)
    op.create_index(op.f('ix_term_progress_term_id'), 'term_progress', ['term_id'], unique=False)
    op.create_index(op.f('ix_term_progress_user_id'), 'term_progress', ['user_id'], unique=False)
    op.create_table('xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=160), nullable=False),
    sa.Column('xp_delta', sa.Integer(), nullable=False),
    sa.Column('lifetime_delta', sa.Integer(), nullable=False),
    sa.Column('raw_xp', sa.Integer(), nullable=False),
    sa.Column('multiplier_pct', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_events_created_at'), 'xp_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_xp_events_event_type'), 'xp_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_xp_events_idempotency_key'), 'xp_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_xp_events_source_id'), 'xp_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_xp_events_user_id'), 'xp_events', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xp_events_user_id'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_source_id'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_idempotency_key'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_event_type'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_created_at'), table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_index(op.f('ix_term_progress_user_id'), table_name='term_progress')
    op.drop_index(op.f('ix_term_progress_term_id'), table_name='term_progress')
    op.drop_index(op.f('ix_term_progress_language'), table_name='term_progress')
    op.drop_table('term_progress')
    op.drop_index(op.f('ix_practice_results_user_id'), table_name='practice_results')
    op.drop_index(op.f('ix_practice_results_session_id'), table_name='practice_results')
    op.drop_index(op.f('ix_practice_results_language'), table_name='practice_results')
    op.drop_index(op.f('ix_practice_results_kind'), table_name='practice_results')
    op.drop_index(op.f('ix_practice_results_created_at'), table_name='practice_results')
    op.drop_table('practice_results')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_login_sessions_user_id'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_token_hash'), table_name='login_sessions')
    op.drop_table('login_sessions')
    op.drop_index(op.f('ix_learning_nudges_user_id'), table_name='learning_nudges')
    op.drop_index(op.f('ix_learning_nudges_read'), table_name='learning_nudges')
    op.drop_index(op.f('ix_learning_nudges_created_at'), table_name='learning_nudges')
    op.drop_table('learning_nudges')
    op.drop_table('gamification_profiles')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_public_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_language'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_game_type'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_exam_results_user_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_language'), table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index(op.f('ix_custom_terms_topic'), table_name='custom_terms')
    op.drop_index(op.f('ix_custom_terms_status'), table_name='custom_terms')
    op.drop_index(op.f('ix_custom_terms_public_id'), table_name='custom_terms')
    op.drop_index(op.f('ix_custom_terms_language'), table_name='custom_terms')
    op.drop_table('custom_terms')
    op.drop_index(op.f('ix_course_day_results_user_id'), table_name='course_day_results')
    op.drop_index(op.f('ix_course_day_results_language'), table_name='course_day_results')
    op.drop_table('course_day_results')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
