from __future__ import annotations

import shutil

import asgi


assert asgi.app
assert asgi.CONTRACT_REPORT.ok

assert asgi.ROUTER_BINDING_REPORT.ok
assert asgi.ROUTER_BINDING_REPORT.system_route_count == 5
assert asgi.ROUTER_BINDING_REPORT.root_mount_order_preserved
assert asgi.ROUTER_BINDING_REPORT.router_module_owned

assert asgi.OBSERVABILITY_ROUTER_BINDING_REPORT.ok
assert asgi.OBSERVABILITY_ROUTER_BINDING_REPORT.metrics_route_bound
assert asgi.OBSERVABILITY_ROUTER_BINDING_REPORT.root_mount_order_preserved
assert asgi.OBSERVABILITY_ROUTER_BINDING_REPORT.router_module_owned
assert asgi.OBSERVABILITY_ROUTER_BINDING_REPORT.renderer_module_owned

assert asgi.SECURITY_BINDING_REPORT.ok
assert asgi.GOVERNANCE_BINDING_REPORT.ok
assert asgi.GOVERNANCE_BINDING_REPORT.rls_bound
assert asgi.GOVERNANCE_BINDING_REPORT.audit_event_bound

assert asgi.LEARNING_BINDING_REPORT.ok
assert asgi.LEARNING_BINDING_REPORT.xp_profile_bound
assert asgi.LEARNING_BINDING_REPORT.xp_award_bound
assert asgi.LEARNING_BINDING_REPORT.srs_schedule_bound

assert asgi.SERVICE_BINDING_REPORT.ok
assert asgi.SERVICE_BINDING_REPORT.user_view_bound
assert asgi.SERVICE_BINDING_REPORT.terms_query_bound
assert asgi.SERVICE_BINDING_REPORT.revision_bound

assert asgi.WORKFLOW_BINDING_REPORT.ok
assert asgi.WORKFLOW_BINDING_REPORT.practice_route_bound
assert asgi.WORKFLOW_BINDING_REPORT.game_start_route_bound
assert asgi.WORKFLOW_BINDING_REPORT.game_finish_route_bound
assert asgi.WORKFLOW_BINDING_REPORT.question_attempt_route_bound
assert asgi.WORKFLOW_BINDING_REPORT.learning_service_captured
assert asgi.WORKFLOW_BINDING_REPORT.terminology_service_captured

assert asgi.AUTH_BINDING_REPORT.ok
assert asgi.AUTH_BINDING_REPORT.current_user_dependency_occurrences > 0
assert asgi.AUTH_BINDING_REPORT.role_dependency_overrides > 0

assert asgi.AUTH_ROUTER_BINDING_REPORT.ok
assert asgi.AUTH_ROUTER_BINDING_REPORT.auth_route_count == 6
assert asgi.AUTH_ROUTER_BINDING_REPORT.local_route_count == 4
assert asgi.AUTH_ROUTER_BINDING_REPORT.oidc_route_count == 2
assert asgi.AUTH_ROUTER_BINDING_REPORT.router_module_owned
assert asgi.AUTH_ROUTER_BINDING_REPORT.current_user_dependency_is_extracted
assert asgi.AUTH_ROUTER_BINDING_REPORT.session_factory_is_extracted

assert asgi.LEARNING_ROUTER_BINDING_REPORT.ok
assert asgi.LEARNING_ROUTER_BINDING_REPORT.learning_route_count == 12
assert asgi.LEARNING_ROUTER_BINDING_REPORT.progress_route_count == 2
assert asgi.LEARNING_ROUTER_BINDING_REPORT.course_route_count == 2
assert asgi.LEARNING_ROUTER_BINDING_REPORT.review_route_count == 2
assert asgi.LEARNING_ROUTER_BINDING_REPORT.gamification_route_count == 4
assert asgi.LEARNING_ROUTER_BINDING_REPORT.preferences_route_count == 2
assert asgi.LEARNING_ROUTER_BINDING_REPORT.router_module_owned
assert asgi.LEARNING_ROUTER_BINDING_REPORT.auth_core_bound
assert asgi.LEARNING_ROUTER_BINDING_REPORT.learning_core_bound
assert asgi.LEARNING_ROUTER_BINDING_REPORT.terminology_service_bound

assert asgi.PRACTICE_GAMES_ROUTER_BINDING_REPORT.ok
assert asgi.PRACTICE_GAMES_ROUTER_BINDING_REPORT.route_count == 4
assert asgi.PRACTICE_GAMES_ROUTER_BINDING_REPORT.practice_route_count == 1
assert asgi.PRACTICE_GAMES_ROUTER_BINDING_REPORT.game_route_count == 2
assert asgi.PRACTICE_GAMES_ROUTER_BINDING_REPORT.question_attempt_route_count == 1
assert asgi.PRACTICE_GAMES_ROUTER_BINDING_REPORT.router_module_owned
assert asgi.PRACTICE_GAMES_ROUTER_BINDING_REPORT.auth_core_bound
assert asgi.PRACTICE_GAMES_ROUTER_BINDING_REPORT.workflow_service_bound
assert asgi.PRACTICE_GAMES_ROUTER_BINDING_REPORT.learning_service_captured
assert asgi.PRACTICE_GAMES_ROUTER_BINDING_REPORT.terminology_service_captured

assert asgi.TERMINOLOGY_ADMIN_ROUTER_BINDING_REPORT.ok
assert asgi.TERMINOLOGY_ADMIN_ROUTER_BINDING_REPORT.route_count == 13
assert asgi.TERMINOLOGY_ADMIN_ROUTER_BINDING_REPORT.public_route_count == 2
assert asgi.TERMINOLOGY_ADMIN_ROUTER_BINDING_REPORT.admin_term_route_count == 10
assert asgi.TERMINOLOGY_ADMIN_ROUTER_BINDING_REPORT.taxonomy_route_count == 1
assert asgi.TERMINOLOGY_ADMIN_ROUTER_BINDING_REPORT.router_module_owned
assert asgi.TERMINOLOGY_ADMIN_ROUTER_BINDING_REPORT.auth_core_bound
assert asgi.TERMINOLOGY_ADMIN_ROUTER_BINDING_REPORT.terminology_service_bound
assert asgi.TERMINOLOGY_ADMIN_ROUTER_BINDING_REPORT.governance_core_bound

assert asgi.PRONUNCIATION_ROUTER_BINDING_REPORT.ok
assert asgi.PRONUNCIATION_ROUTER_BINDING_REPORT.route_count == 3
assert asgi.PRONUNCIATION_ROUTER_BINDING_REPORT.status_route_count == 1
assert asgi.PRONUNCIATION_ROUTER_BINDING_REPORT.post_audio_route_count == 1
assert asgi.PRONUNCIATION_ROUTER_BINDING_REPORT.legacy_get_enabled
assert asgi.PRONUNCIATION_ROUTER_BINDING_REPORT.legacy_get_route_count == 1
assert asgi.PRONUNCIATION_ROUTER_BINDING_REPORT.router_module_owned
assert asgi.PRONUNCIATION_ROUTER_BINDING_REPORT.auth_core_bound
assert asgi.PRONUNCIATION_ROUTER_BINDING_REPORT.payload_schema_preserved
assert asgi.PRONUNCIATION_ROUTER_BINDING_REPORT.tts_max_chars_preserved
assert asgi.PRONUNCIATION_ROUTER_BINDING_REPORT.legacy_tts_handlers_captured

assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.ok
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.route_count == 6
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.admin_route_count == 4
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.manager_route_count == 2
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.route_names_preserved
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.response_classes_preserved
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.payload_schemas_preserved
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.root_mount_order_preserved
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.router_module_owned
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.auth_core_bound
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.user_service_bound
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.terminology_service_bound
assert asgi.USERS_MANAGER_ROUTER_BINDING_REPORT.governance_core_bound

assert shutil.which("espeak-ng")
print("OK: modular runtime bindings, extracted routers and offline TTS binary verified")
