#!/usr/bin/env python3
from pathlib import Path
import sys
root=Path(__file__).resolve().parents[1]
checks=[]
def chk(name, cond): checks.append((name,bool(cond)))
models=(root/'backend/app/db/models.py').read_text()
svc=(root/'backend/app/services/approval_governance.py').read_text()
plat=(root/'backend/app/api/contexts/platform_operations.py').read_text()
conf=(root/'backend/app/api/contexts/configuration_change.py').read_text()
mig=(root/'backend/app/db/migrations.py').read_text()
rt=(root/'backend/app/core/runtime_contract.py').read_text()
chk('current version 6.3.6', 'APP_VERSION = "6.3.34"' in rt and 'SCHEMA_VERSION = "6.3.13"' in rt)
for table in ['engineering_approval_policies','engineering_approval_cases','engineering_approval_records','engineering_release_packages','engineering_release_package_items']:
    chk(f'model table {table}', table in models)
chk('approval records are one per case/stage', 'uq_approval_record_case_stage' in models)
chk('approval case cycles unique', 'uq_approval_case_entity_cycle' in models)
chk('maker checker enforced', 'Maker-checker rule' in svc)
chk('segregation of duties enforced', 'Segregation of duties' in svc)
chk('snapshot drift blocks approval', 'Entity changed after submission' in svc)
chk('approval evidence hash chain', 'previous_hash' in svc and 'record_hash' in svc and 'approval_chain_integrity_valid' in svc)
chk('policy snapshot frozen into case', 'policy_snapshot_json=pp' in svc)
chk('release package verifies items before release', 'verify_package(db,pkg)' in svc and 'changed after approval' in svc)
chk('release package cannot bypass object approval', 'must be approved before package submission' in svc)
chk('PLM/PDM documents remain external authority', 'authority="plm_pdm" if et=="document"' in svc)
chk('no document mutation in release path', 'doc.status=' not in svc and 'doc.sha256=' not in svc)
chk('MGC revision supersession controlled', 'superseded_by_release_package' in svc)
chk('qualified signature not falsely claimed', 'qualified_electronic_signature":False' in svc)
chk('policy API admin surface present', '/approval-policies' in plat)
chk('generic approval submit present', '/approvals/{entity_type}/{entity_id}/submit' in plat)
chk('legacy direct WI approval disabled by default', 'allow_legacy_direct_wi_approval: bool = False' in (root/'backend/app/core/config.py').read_text() and 'Direct work-instruction approval is disabled' in (root/'backend/app/api/contexts/manufacturing_quality.py').read_text())
chk('WI approval keeps translation/station/steps safety gates', 'Current reviewed Russian translation is required before approval' in plat and 'must be linked to a station before approval' in plat and 'explicit steps before approval' in plat)
chk('layout approval requires station placement', 'at least one station placement before approval' in plat)
chk('approval decision endpoint present', '/approvals/{case_id}/decision' in plat)
chk('release package create/list surface present', '/release-packages' in conf)
chk('release package explicit release surface present', '/release-packages/{package_id}/release' in conf)
chk('migration marker present', 'ensure_v635_schema' in mig and "'6.3.5'" in mig)
passed=sum(x for _,x in checks)
for name,ok in checks: print(('PASS' if ok else 'FAIL')+' | '+name)
print(f'\n{passed}/{len(checks)} PASS')
sys.exit(0 if passed==len(checks) else 1)
