#!/usr/bin/env python3
"""Static fail-closed verification for v6.3.34 Blue/Green Cutover & Automated Rollback Safety."""
from __future__ import annotations
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def ck(name, ok, detail=''): checks.append((name,bool(ok),detail))
def txt(path): return (ROOT/path).read_text()

runtime=txt('backend/app/core/runtime_contract.py')
config=txt('backend/app/core/config.py')
cut=txt('backend/app/core/cutover_safety.py')
deploy=txt('backend/app/core/deployment_safety.py')
ops=txt('backend/app/api/operations_routes.py')
support=txt('backend/app/services/production_support.py')
compose=txt('docker-compose.yml')
overlay=txt('docker-compose.bluegreen.yml')
gateway=txt('ops/gateway/templates/default.conf.template')
script=txt('scripts/blue_green_cutover.sh')
rollback=txt('scripts/blue_green_rollback.sh')
finalize=txt('scripts/blue_green_finalize.sh')
contract=txt('scripts/cutover_contract_check.py')

ck('app_version_6317','APP_VERSION = "6.3.34"' in runtime)
ck('schema_unchanged_6313','SCHEMA_VERSION = "6.3.13"' in runtime)
ck('blue_green_enabled','blue_green_enabled: bool = True' in config)
ck('slot_config','deployment_slot: str = "stable"' in config)
ck('candidate_samples','cutover_candidate_min_ready_samples: int = 3' in config)
ck('post_switch_samples','cutover_post_switch_samples: int = 5' in config)
ck('failure_threshold','cutover_failure_threshold: int = 2' in config)
ck('rollback_skew_one','cutover_max_patch_rollback_skew: int = 1' in config)
ck('heartbeat_slot','"deployment_slot"' in deploy)
ck('rollback_same_schema','target_schema != SCHEMA_VERSION' in cut and 'schema_rollback_forbidden' in cut)
ck('rollback_patch_bound','rollback_patch_skew_exceeded' in cut)
ck('rollback_newer_forbidden','target_is_newer_than_current' in cut)
ck('cutover_snapshot','def cutover_safety_snapshot' in cut)
ck('operations_endpoint','@router.get("/cutover-safety")' in ops)
ck('operations_admin','def cutover_safety' in ops and '_admin(identity)' in ops[ops.index('def cutover_safety'):ops.index('def cutover_safety')+220])
ck('support_bundle_cutover','"cutover-safety.json"' in support)
ck('operations_summary_cutover','"cutover_safety": cutover' in support)
ck('gateway_api_variable','proxy_pass http://${API_UPSTREAM};' in gateway)
ck('gateway_frontend_variable','proxy_pass http://${FRONTEND_UPSTREAM};' in gateway)
ck('gateway_default_stable','API_UPSTREAM: ${API_UPSTREAM:-api:8080}' in compose and 'FRONTEND_UPSTREAM: ${FRONTEND_UPSTREAM:-frontend:8080}' in compose)
ck('candidate_api_service',re.search(r'^  api-candidate:',overlay,re.M) is not None)
ck('candidate_frontend_service',re.search(r'^  frontend-candidate:',overlay,re.M) is not None)
ck('candidate_slot','DEPLOYMENT_SLOT: candidate' in overlay)
ck('candidate_not_public','ports:' not in overlay)
ck('cutover_contract_script','schema_mismatch' in contract and 'cutover_patch_skew_exceeded' in contract)
ck('cutover_requires_stable_running','Stable api service is not running' in script)
ck('resilience_release_gate','MGC_RESILIENCE_CERTIFICATION_REPORT' in script and 'resilience_release_guard.py' in script)
ck('resilience_source_bundle_gate',all(name in script for name in ('MGC_RESILIENCE_EVIDENCE','MGC_RESILIENCE_EVIDENCE_SIGNATURE','MGC_RESILIENCE_PUBLIC_KEY','MGC_RESILIENCE_BASELINE','MGC_RESILIENCE_CAMPAIGN')))
ck('candidate_consecutive_ready','consecutive' in script and 'READY_SAMPLES' in script)
ck('candidate_health_before_switch',script.index('http://api-candidate:8080/api/v1/health/ready') < script.index('API_UPSTREAM="api-candidate:8080"'))
ck('gateway_switch_explicit','API_UPSTREAM="api-candidate:8080"' in script)
ck('post_switch_probe','POST_SAMPLES' in script and 'http://127.0.0.1:8080/api/v1/health/ready' in script)
ck('optional_slo_probe','CUTOVER_SLO_PROBE_CMD' in script)
ck('automatic_rollback','scripts/blue_green_rollback.sh' in script and 'FAIL_THRESHOLD' in script)
ck('state_is_local_operational','storage/.mgc-deployment' in script and 'chmod 600' in script)
ck('rollback_contract_guard','cutover_contract_check.py' in rollback and '--rollback' in rollback)
ck('rollback_stable_upstream','API_UPSTREAM="api:8080"' in rollback)
ck('rollback_keeps_candidate','Candidate remains isolated for diagnostics' in rollback)
ck('finalize_human_invoked','scripts/rolling_upgrade.sh' in finalize and 'candidate_active' in finalize)
ck('finalize_stops_candidate','stop api-candidate frontend-candidate' in finalize)
ck('production_not_auto_authorized','production_authorized": False' in cut)
ck('no_db_migration_6317','ensure_v6317_schema' not in txt('backend/app/db/migrations.py'))

failed=[x for x in checks if not x[1]]
for n,ok,d in checks: print(f"{'PASS' if ok else 'FAIL'} {n}"+(f' — {d}' if d else ''))
print(f'SUMMARY {len(checks)-len(failed)}/{len(checks)} PASS')
if failed: raise SystemExit(1)
