#!/usr/bin/env python3
from pathlib import Path
import sys
root=Path(__file__).resolve().parents[1]
checks=[]
def ck(name,cond): checks.append((name,bool(cond)))
models=(root/'backend/app/db/models.py').read_text()
security=(root/'backend/app/core/security.py').read_text()
config=(root/'backend/app/core/config.py').read_text()
svc=(root/'backend/app/services/identity_policy.py').read_text()
gov=(root/'backend/app/services/approval_governance.py').read_text()
plat=(root/'backend/app/api/contexts/platform_operations.py').read_text()
conf=(root/'backend/app/api/contexts/configuration_change.py').read_text()
mig=(root/'backend/app/db/migrations.py').read_text()
rt=(root/'backend/app/core/runtime_contract.py').read_text()
ui=(root/'frontend/src/main.tsx').read_text()
ck('version 6.3.6','APP_VERSION = "6.3.34"' in rt and 'SCHEMA_VERSION = "6.3.13"' in rt)
ck('identity policy model','engineering_identity_policies' in models)
ck('delegation model','engineering_identity_delegations' in models)
ck('approval submit identity evidence','submitted_identity_json' in models and 'submitted_identity' in gov)
ck('approval decision identity evidence','identity_snapshot_json' in models and 'assurance_json' in models and 'identity_snapshot_payload' in gov)
ck('release identity evidence','released_identity_json' in models and 'released_identity' in gov)
for f in ['subject','auth_mode','issuer','acr','auth_time','client_id','is_service_account']:
    ck(f'identity field {f}',f'{f}:' in security)
ck('service account claim configurable','oidc_actor_type_claim' in config and 'oidc_service_account_values' in config)
ck('service account not guessed from username','never infer service-account status from a username prefix' in security)
ck('human-only privileged actions','HUMAN_ONLY_ACTIONS' in svc and 'Human identity required' in svc)
ck('scoped policy resolution','resolve_identity_policy' in svc and '_specificity' in svc)
ck('deny wins','explicitly denies one of the current groups' in svc)
ck('allow groups enforced','not in an allowed group' in svc)
ck('OIDC enforcement','Corporate OIDC identity is required' in svc)
ck('fresh-auth enforcement','Authentication is too old' in svc and 'privileged_reauth_max_age_seconds' in config)
ck('ACR enforcement','Authentication assurance level' in svc)
ck('delegation is narrow','DELEGATABLE_ACTIONS = {"approval_decision"}' in svc)
ck('delegation cannot mint admin','engineering_admin_group_set' in svc and 'Delegation may never mint Engineering Admin authority' in svc)
ck('policy API','/identity/policies' in plat)
ck('delegation API','/identity/delegations' in plat and '/identity/delegations/{delegation_id}/revoke' in plat)
ck('approval decision PEP','action="approval_decision"' in plat and 'effective_groups' in plat)
ck('approval submit PEP','action="approval_submit"' in plat)
ck('release create PEP','action="release_package_create"' in conf)
ck('release submit PEP','action="release_package_submit"' in conf)
ck('final release PEP','action="release_package_release"' in conf)
ck('release manifest endpoint','/release-packages/{package_id}/manifest' in conf and 'production_writeback' in gov)
ck('qualified signature not falsely claimed','qualified_electronic_signature' in gov and 'False' in gov)
ck('optional RLS scoped to governance','governance_postgres_rls_enabled' in config and 'engineering_identity_policies ENABLE ROW LEVEL SECURITY' in mig and 'engineering_identity_delegations ENABLE ROW LEVEL SECURITY' in mig)
ck('existing ACL explicitly preserved','existing engineering ACLs remain unchanged' in mig)
ck('migration 6.3.6','def ensure_v636_schema' in mig and "'6.3.6'" in mig)
ck('admin UI identity metrics','Enterprise Identity & Approval · v6.3.6' in ui and 'active_identity_policies' in ui and 'active_delegations' in ui)
ck('no token stored in identity snapshot','"token"' not in security[security.find('def identity_snapshot'):])
passed=sum(ok for _,ok in checks)
for n,ok in checks: print(('PASS' if ok else 'FAIL')+' | '+n)
print(f'\n{passed}/{len(checks)} PASS')
sys.exit(0 if passed==len(checks) else 1)
