#!/usr/bin/env python3
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
checks=[]
def ck(name, ok):
    checks.append((name,bool(ok))); print(('PASS' if ok else 'FAIL')+': '+name)
def text(p): return (ROOT/p).read_text(encoding='utf-8')
rt=text(Path('backend/app/core/runtime_contract.py'))
prov=text(Path('backend/app/core/release_provenance.py'))
gov=text(Path('backend/app/core/release_provenance_governance.py'))
cli=text(Path('scripts/release_provenance_registry.py'))
cfg=text(Path('backend/app/core/config.py'))
ops=text(Path('backend/app/api/operations_routes.py'))
mk=text(Path('Makefile'))
ck('runtime version 6.3.34','APP_VERSION = "6.3.34"' in rt and 'SCHEMA_VERSION = "6.3.13"' in rt)
ck('bounded signing key validity','valid_days: int = 180' in prov and 'expires_at' in prov and 'rotation_warning_days' in prov)
ck('expired keys rejected for new evidence','signing key is expired' in prov)
ck('historical key validity replay','signer_expired_at_registration' in prov and 'signer_before_validity' in prov)
ck('retention policy event','RETENTION_POLICY_SET' in prov and 'mgc-release-retention-policy-v1' in gov)
ck('automatic deletion forbidden','"automatic_deletion": False' in gov and 'ledger_metadata_permanent' in gov)
ck('legal hold events','LEGAL_HOLD_PLACED' in prov and 'LEGAL_HOLD_RELEASED' in prov)
ck('checkpoint event','CHECKPOINT_CREATED' in prov and 'mgc-release-provenance-checkpoint-v1' in gov)
ck('checkpoint binds tip','covered_tip_sequence' in gov and 'covered_tip_sha256' in gov)
ck('external anchor event','EXTERNAL_ANCHOR_RECORDED' in prov and 'mgc-release-anchor-receipt-v1' in gov)
ck('external anchor hash match','external anchor receipt hash mismatch' in gov)
ck('anchor freshness governance','external_anchor_stale' in gov and 'anchor_max_age_hours' in gov)
ck('WORM receipt event','WORM_RECEIPT_RECORDED' in prov and 'mgc-release-worm-receipt-v1' in gov)
ck('WORM retention cannot shorten','WORM receipt retention is shorter than requested' in gov)
ck('WORM checkpoint binding','worm_receipt_object_mismatch' in gov)
ck('generic adapter no shell','shell=False' in gov and 'JSON array of argv strings' in gov)
ck('adapter environment minimized','SSL_CERT_FILE' in gov and 'os.environ.items()' in gov)
ck('governance required trust fail closed','required_external_anchor_unavailable' in gov and 'required_worm_receipt_unavailable' in gov)
ck('missing trust is conditional','"CONDITIONAL" if warnings' in gov)
ck('production never auto authorized','"production_authorized": False' in gov)
ck('offline auditor bundle schema','mgc-release-auditor-bundle-v1' in gov)
ck('auditor bundle path traversal defense','unsafe_zip_member' in gov and 'symlink_zip_member' in gov)
ck('auditor bundle replays registry','verify_registry(dest / "registry")' in gov)
ck('CLI retention/legal hold','retention-set' in cli and 'hold-place' in cli and 'hold-release' in cli)
ck('CLI checkpoint/anchor/WORM','checkpoint' in cli and 'worm-seal' in cli and 'adapter-command-json' in cli)
ck('CLI auditor export/verify','auditor-export' in cli and 'auditor-verify' in cli)
ck('config anchor requirement','release_provenance_require_external_anchor' in cfg)
ck('config WORM requirement','release_provenance_require_worm_receipt' in cfg)
ck('config checkpoint freshness','release_provenance_checkpoint_max_age_hours' in cfg)
ck('operations privacy safe governance','verify_governance' in ops and '"governance"' in ops)
seg=ops[ops.index('@router.get("/release-provenance")'):ops.index('@router.get("/authoritative-ha")')]
ck('operations does not expose registry path','"path"' not in seg and 'public_key_object_sha256' not in seg)
ck('Makefile governance targets','release-provenance-checkpoint' in mk and 'release-provenance-auditor-export' in mk)
failed=[n for n,o in checks if not o]
if failed: raise SystemExit('v6.3.34 external trust/retention preflight failed: '+', '.join(failed))
print(f'PASS: v6.3.34 External Trust Anchoring & Evidence Retention Governance preflight ({len(checks)}/{len(checks)})')
