#!/usr/bin/env python3
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def ck(name, cond): checks.append((name,bool(cond)))
rt=(ROOT/'backend/app/core/runtime_contract.py').read_text(encoding='utf-8')
res=(ROOT/'backend/app/core/resilience.py').read_text(encoding='utf-8')
health=(ROOT/'backend/app/core/operational_health.py').read_text(encoding='utf-8')
vector=(ROOT/'backend/app/services/vector_store.py').read_text(encoding='utf-8')
ai=(ROOT/'backend/app/adapters/ai.py').read_text(encoding='utf-8')
vision=(ROOT/'backend/app/services/drawing_vision.py').read_text(encoding='utf-8')
cad=(ROOT/'backend/app/integrations/cad_gateway.py').read_text(encoding='utf-8')
ops=(ROOT/'backend/app/api/operations_routes.py').read_text(encoding='utf-8')
support=(ROOT/'backend/app/services/production_support.py').read_text(encoding='utf-8')
jobs=(ROOT/'backend/app/services/background_jobs.py').read_text(encoding='utf-8')
config=(ROOT/'backend/app/core/config.py').read_text(encoding='utf-8')
ck('application version 6.3.34', 'APP_VERSION = "6.3.34"' in rt)
ck('schema unchanged 6.3.13', 'SCHEMA_VERSION = "6.3.13"' in rt)
ck('breaker registry', 'class ResilienceRegistry' in res)
ck('closed/open/half-open states', all(x in res for x in ['"closed"','"open"','"half_open"']))
ck('bounded failure threshold', 'resilience_failure_threshold' in config)
ck('cooldown configuration', 'resilience_open_seconds' in config)
ck('breaker non-authoritative policy', 'breaker_state_authoritative' in res and 'False' in res)
ck('qdrant fallback policy', 'qdrant_failure_allows_lexical_fallback' in res)
ck('AI evidence fallback policy', 'ai_failure_allows_evidence_only_answer' in res)
ck('CAD does not block core policy', 'cad_failure_does_not_disable_documents_bom_wi' in res)
ck('qdrant calls circuit protected', 'circuit_allows("qdrant")' in vector and 'record_failure("qdrant"' in vector)
ck('LLM calls circuit protected', 'circuit_allows("local_ai")' in ai and 'record_failure("local_ai"' in ai)
ck('VLM calls circuit protected', 'circuit_allows("vlm")' in vision and 'record_failure("vlm"' in vision)
ck('CAD gateway circuit protected', 'circuit_allows("native_cad")' in cad and 'record_failure("native_cad"' in cad)
ck('Redis job dispatch circuit protected', 'circuit_allows("redis")' in jobs and 'record_failure("redis"' in jobs and 'record_success("redis"' in jobs)
ck('core readiness policy exposes resilience', '"resilience": resilience_snapshot()' in health)
ck('strict optional readiness opt-in', 'resilience_strict_dependency_readiness' in health)
ck('operations resilience endpoint', '@router.get("/resilience")' in ops)
ck('support bundle carries resilience', '"resilience.json": resilience_snapshot()' in support)
ck('operations summary carries resilience', '"resilience": resilience' in support)
ck('Prometheus circuit state metric', 'mgc_resilience_circuit_state' in res)
ck('Prometheus brownout metric', 'mgc_resilience_brownout' in res)
ck('no automatic engineering decision replay', 'optional_failure_blocks_engineering_core' in res)
failed=[n for n,ok in checks if not ok]
if failed: raise SystemExit('v6.3.34 operational resilience preflight failed: '+', '.join(failed))
print(f'PASS: v6.3.34 Operational Resilience preflight ({len(checks)}/{len(checks)})')
