#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, os, re, shutil, subprocess, sys
from collections import defaultdict
from pathlib import Path
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name, parse_wheel_filename
ROOT=Path(__file__).resolve().parents[1]

def expanded(path:Path, seen=None):
    seen=set() if seen is None else seen; path=path.resolve()
    if path in seen: return []
    seen.add(path); out=[]
    for raw in path.read_text().splitlines():
        line=raw.strip()
        if not line or line.startswith('#'): continue
        if line.startswith('-r ') or line.startswith('--requirement '): out.extend(expanded(path.parent/line.split(None,1)[1],seen))
        else: out.append(line)
    return out

def sha(path):
    h=hashlib.sha256()
    with path.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024),b''): h.update(b)
    return h.hexdigest()

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--profile',choices=['core','ai','advanced'],required=True); ap.add_argument('--index-url',default=os.getenv('PIP_INDEX_URL','')); ap.add_argument('--trusted-host',default=''); ap.add_argument('--clean',action='store_true',default=True); args=ap.parse_args()
    req=ROOT/f'backend/requirements-{args.profile}.txt'; wheels=ROOT/f'backend/wheelhouse/{args.profile}'; lock=ROOT/f'backend/locks/requirements-{args.profile}.lock.txt'
    if args.clean and wheels.exists(): shutil.rmtree(wheels)
    wheels.mkdir(parents=True,exist_ok=True)
    cmd=[sys.executable,'-m','pip','download','--only-binary=:all:','--dest',str(wheels),'-r',str(req)]
    if args.index_url: cmd += ['--index-url',args.index_url]
    if args.trusted_host: cmd += ['--trusted-host',args.trusted_host]
    print('RUN',' '.join(cmd)); subprocess.run(cmd,check=True)
    grouped=defaultdict(list); versions={}; manifest=[]
    for whl in sorted(wheels.glob('*.whl')):
        name,version,_,_=parse_wheel_filename(whl.name); key=canonicalize_name(str(name)); versions[key]=str(version); digest=sha(whl); grouped[key].append(digest); manifest.append({'name':whl.name,'sha256':digest,'bytes':whl.stat().st_size})
    if not manifest: raise SystemExit('No wheels downloaded')
    # Ensure every declared top-level requirement is represented by a compatible resolved wheel.
    for raw in expanded(req):
        r=Requirement(raw); key=canonicalize_name(r.name); ver=versions.get(key)
        if ver is None: raise SystemExit(f'Missing direct requirement in wheelhouse: {r.name}')
        if r.specifier and not r.specifier.contains(ver,prereleases=True): raise SystemExit(f'Resolved {r.name}=={ver} violates {r.specifier}')
    lines=['# Generated by scripts/prepare_python_lock.py against an approved mirror.','# Platform-specific resolved lock; install with --no-index --require-hashes.']
    for key in sorted(grouped):
        line=f'{key}=={versions[key]}'
        hashes=sorted(set(grouped[key]))
        if len(hashes)==1: line += f' --hash=sha256:{hashes[0]}'
        else:
            line += ' \\\n' + ' \\\n'.join(f'    --hash=sha256:{h}' for h in hashes)
        lines.append(line)
    lock.write_text('\n'.join(lines)+'\n')
    meta={'schema':'mgc.python-wheelhouse.v1','release':'6.3.34','profile':args.profile,'python':sys.version.split()[0],'source_requirement':str(req.relative_to(ROOT)),'source_requirement_sha256':sha(req),'files':manifest}
    (wheels/'WHEELHOUSE_MANIFEST.json').write_text(json.dumps(meta,indent=2)+'\n')
    print('WROTE',lock.relative_to(ROOT),len(grouped),'packages;',len(manifest),'wheels')
if __name__=='__main__': main()
