#!/usr/bin/env python3
"""Static fail-closed checks for v6.3.7 Release Handover & Integration Safety."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def read(rel): return (ROOT/rel).read_text()
rt=read('backend/app/core/runtime_contract.py')
cfg=read('backend/app/core/config.py')
models=read('backend/app/db/models.py')
mig=read('backend/app/db/migrations.py')
svc=read('backend/app/services/engineering_handover.py')
port=read('backend/app/ports/handover.py')
adapter=read('backend/app/adapters/handover.py')
cc=read('backend/app/api/contexts/configuration_change.py')
po=read('backend/app/api/contexts/platform_operations.py')
idp=read('backend/app/services/identity_policy.py')
env=read('.env.example')
ui=read('frontend/src/main.tsx')
ops=read('backend/app/services/production_support.py')
checks=[]
def ck(name,ok,detail=''):
    checks.append((name,bool(ok),detail))
ck('version 6.3.7','APP_VERSION = "6.3.34"' in rt and 'SCHEMA_VERSION = "6.3.13"' in rt)
ck('write disabled default','handover_write_enabled: bool = False' in cfg)
ck('dry run default','handover_dry_run_default: bool = True' in cfg)
ck('empty target allowlist default','handover_allowed_target_codes: str = ""' in cfg)
ck('empty host allowlist default','handover_allowed_hosts: str = ""' in cfg)
ck('bounded retries','handover_max_attempts' in cfg and 'retry budget exhausted' in svc)
ck('bounded reconciliation age','handover_reconciliation_max_age_seconds' in cfg and 'oldest_unreconciled_age_seconds' in svc)
ck('target model','class EngineeringHandoverTarget' in models)
ck('job model','class EngineeringHandoverJob' in models)
ck('receipt model','class EngineeringHandoverReceipt' in models)
ck('job idempotency unique','uq_handover_job_target_idempotency' in models)
ck('immutable db trigger','mgc_v637_handover_immutable' in mig and 'handover command fields are immutable' in mig)
ck('migration marker','def ensure_v637_schema' in mig and "'6.3.7'" in mig)
ck('write port','class HandoverWritePort' in port)
ck('rest adapter','class GenericRestHandoverAdapter' in adapter)
ck('adapter relative path','relative integration-gateway path' in adapter)
ck('PLM PDM MES only','TARGET_SOURCE_DOMAINS = {"plm", "pdm", "mes"}' in svc)
ck('released package only','Only a released Engineering Release Package can be handed over' in svc)
ck('target project allowlist','not allowlisted for this target' in svc)
ck('target area allowlist','Manufacturing area is not allowlisted' in svc)
ck('idempotency capability required','must guarantee Idempotency-Key semantics' in svc)
ck('receipt/reconcile contract','Write target requiring receipt must configure reconciliation endpoint' in svc)
ck('global write gate','External handover write-back is globally disabled' in svc)
ck('target code allowlist gate','HANDOVER_ALLOWED_TARGET_CODES' in svc)
ck('host allowlist gate','HANDOVER_ALLOWED_HOSTS' in svc)
ck('production https gate','Production handover gateway must use HTTPS' in svc)
ck('maker checker','handover creator cannot authorize external write' in svc)
ck('human checker','Human checker identity required' in svc)
ck('maker cannot execute','Maker cannot execute own outbound handover' in svc)
ck('fresh manifest before execute','Release Package/manifest changed after handover command creation' in svc)
ck('idempotency header','Idempotency-Key' in svc and 'X-MGC-Request-SHA256' in svc)
ck('receipt mandatory','Target did not return required reconciliation receipt' in svc)
ck('reconciliation hash proof','missing_target_hash_proof' in svc and 'manifest_sha256_mismatch' in svc)
ck('no machine control','"machine_control":False' in svc)
ck('identity actions',all(x in idp for x in ('handover_create','handover_authorize','handover_execute','handover_reconcile','handover_target_admin')))
ck('job create API','/release-packages/{package_id}/handover-jobs' in cc)
ck('authorize API','/handover-jobs/{job_id}/authorize' in cc)
ck('execute API','/handover-jobs/{job_id}/execute' in cc)
ck('reconcile API','/handover-jobs/{job_id}/reconcile' in cc)
ck('target admin API','/handover/targets' in po)
ck('handover summary API','/handover/summary' in po)
ck('operations summary integration','handover_dashboard(db)' in ops and '"handover": handover' in ops)
ck('prometheus handover metrics','mgc_handover_jobs' in ops and 'mgc_handover_oldest_unreconciled_age_seconds' in ops and 'mgc_handover_write_enabled' in ops)
ck('support bundle includes handover indirectly','operations-summary.json' in ops and 'operations_summary(db' in ops)
ck('safe env defaults','HANDOVER_WRITE_ENABLED=false' in env and 'HANDOVER_ALLOWED_TARGET_CODES=' in env and 'HANDOVER_ALLOWED_HOSTS=' in env and 'HANDOVER_RECONCILIATION_MAX_AGE_SECONDS=3600' in env)
ck('admin UI posture','Release Handover · v6.3.7' in ui and 'read-only' in ui and 'PLC/robot/machine control отсутствует' in ui)
failed=[x for x in checks if not x[1]]
for n,ok,d in checks: print(f"{'PASS' if ok else 'FAIL'} {n}"+(f' — {d}' if d else ''))
print(f"SUMMARY {len(checks)-len(failed)}/{len(checks)} PASS")
if failed: raise SystemExit(1)
