#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def ck(name,ok):
    checks.append((name,bool(ok))); print(('PASS' if ok else 'FAIL')+': '+name)
def has(p,t):
    return t in (ROOT/p).read_text(encoding='utf-8')
rt=(ROOT/'backend/app/core/runtime_contract.py').read_text(encoding='utf-8')
core=(ROOT/'backend/app/core/release_provenance.py').read_text(encoding='utf-8')
cli=(ROOT/'scripts/release_provenance_registry.py').read_text(encoding='utf-8')
ops=(ROOT/'backend/app/api/operations_routes.py').read_text(encoding='utf-8')
cfg=(ROOT/'backend/app/core/config.py').read_text(encoding='utf-8')
mk=(ROOT/'Makefile').read_text(encoding='utf-8')
ck('runtime version v6.3.34','APP_VERSION = "6.3.34"' in rt and 'SCHEMA_VERSION = "6.3.13"' in rt)
ck('provenance event schema','mgc-release-provenance-event-v1' in core)
ck('content addressed object store','objects" / "sha256' in core)
ck('append-only event paths','immutable provenance path already exists' in core)
ck('exclusive append lock','fcntl.LOCK_EX' in core)
ck('symlink fail closed','symlink is forbidden in provenance path' in core)
ck('event parent hash chain','parent_event_sha256' in core)
ck('event sequence verification','"sequence"' in core and 'expected_seq' in core)
ck('event filename digest verification','reasons.append("filename")' in core)
ck('object size and hash verification','object_size:' in core and 'object hash mismatch' in core)
ck('private keys rejected','private key material must never enter the provenance registry' in core)
ck('key registration events','KEY_REGISTERED' in core)
ck('key revocation events','KEY_REVOKED' in core)
ck('historical trust replay','signer_not_active_at_registration' in core)
ck('acceptance registration','ACCEPTANCE_REGISTERED' in core)
ck('baseline registration','BASELINE_REGISTERED' in core)
ck('load evidence registration','LOAD_EVIDENCE_REGISTERED' in core)
ck('failover evidence registration','FAILOVER_EVIDENCE_REGISTERED' in core)
ck('detached openssl verification','openssl' in core and '-verify' in core)
ck('cross version comparison','def compare_releases' in core)
ck('audit report','mgc-release-provenance-audit-v1' in core and 'def build_audit_report' in core)
ck('production never auto authorized','"production_authorized": False' in core)
ck('CLI key rotation/revocation','key-register' in cli and 'key-revoke' in cli)
ck('CLI evidence registration','acceptance-register' in cli and 'baseline-register' in cli and 'load-register' in cli)
ck('CLI verify/compare/audit','verify' in cli and 'compare' in cli and 'audit' in cli)
ck('registry disabled by default','release_provenance_registry_enabled: bool = False' in cfg)
ck('controlled registry path','release_provenance_registry_path' in cfg)
ck('admin operations summary','@router.get("/release-provenance")' in ops and '_admin(identity)' in ops)
ck('operations API no raw registry path','settings.release_provenance_registry_path' in ops and '"path"' not in ops[ops.index('@router.get("/release-provenance")'):ops.index('@router.get("/authoritative-ha")')])
ck('Makefile provenance targets','release-provenance-preflight' in mk and 'release-provenance-verify' in mk)
ck('acceptance pipeline auto-register',has(Path('scripts/release_acceptance_pipeline.py'),'--provenance-registry') and has(Path('scripts/release_acceptance_pipeline.py'),'kind="acceptance"'))
ck('baseline promotion auto-register',has(Path('scripts/promote_acceptance_baseline.py'),'--provenance-registry') and has(Path('scripts/promote_acceptance_baseline.py'),"kind='baseline'"))
ck('uninitialized registry not healthy','UNINITIALIZED' in core and 'registry_uninitialized' in core)
failed=[n for n,o in checks if not o]
if failed: raise SystemExit('v6.3.34 release provenance preflight failed: '+', '.join(failed))
print(f'PASS: v6.3.34 Acceptance Evidence Registry & Release Provenance Ledger preflight ({len(checks)}/{len(checks)})')
